<?xml version="1.0"?>
<package format="2">
    <name>wolf_planner_interface</name>
    <version>0.0.0</version>
    <description>Legged interface base on OCS2</description>
    <maintainer email="todo@gmail.com">ToDo</maintainer>

    <license>BSD</license>
    <author email="todo@gmail.com">ToDo</author>

    <buildtool_depend>catkin</buildtool_depend>
    <depend>roscpp</depend>
    <depend>ocs2_legged_robot</depend>
    <depend>ocs2_self_collision</depend>
    <depend>pinocchio</depend>

</package>
