<?xml version="1.0"?>
<package format="2">
    <name>wolf_planner_interface</name>
    <version>0.0.1</version>
    <description>Legged interface base on OCS2</description>
    <maintainer email="todo@gmail.com">ToDo</maintainer>

    <license>BSD</license>
    <author email="todo@gmail.com">ToDo</author>

    <buildtool_depend>catkin</buildtool_depend>

    <depend>roscpp</depend>
    <depend>pluginlib</depend>
    <depend>wolf_msgs</depend>
    <depend>wolf_controller_utils</depend>

    <depend>pinocchio</depend>
    <depend>hpp-fcl</depend>

    <depend>ocs2_legged_robot</depend>
    <depend>ocs2_legged_robot_ros</depend>
    <depend>ocs2_self_collision</depend>
    <depend>ocs2_self_collision_visualization</depend>

    <!-- The export tag contains other, unspecified, tags -->
    <export>
      <controller_interface plugin="${prefix}/wolf_planner_default_plugins.xml"/>
    </export>

</package>
