<?xml version="1.0"?>
<package format="2">
    <name>wolf_planner_adaptive</name>
    <version>0.0.1</version>
    <description>Adaptive planner based on OCS2</description>
    <maintainer email="gennaro.raiola@gmail.com">Gennaro Raiola</maintainer>

    <license>BSD</license>
    <author email="gennaro.raiola@gmail.com">Gennaro Raiola</author>

    <buildtool_depend>catkin</buildtool_depend>

    <depend>roscpp</depend>
    <depend>pluginlib</depend>
    <depend>wolf_msgs</depend>
    <depend>wolf_planner_interface</depend>

    <depend>pinocchio</depend>
    <depend>hpp-fcl</depend>

    <depend>ocs2_legged_robot</depend>
    <depend>ocs2_legged_robot_ros</depend>

</package>
