<?xml version="1.0"?>
<package format="2">
    <name>wolf_planner_perceptive</name>
    <version>0.0.1</version>
    <description>Perceptive planner based on OCS2</description>
    <maintainer email="gennaro.raiola@gmail.com">ToDo</maintainer>

    <license>BSD</license>
    <author email="gennaro.raiola@gmail.com">ToDo</author>

    <buildtool_depend>catkin</buildtool_depend>

    <depend>roscpp</depend>
    <depend>pluginlib</depend>
    <depend>wolf_planner_interface</depend>
    <depend>convex_plane_decomposition_msgs</depend>
    <depend>convex_plane_decomposition_ros</depend>
    <depend>grid_map_sdf</depend>
    <depend>pinocchio</depend>

    <depend>ocs2_legged_robot</depend>
    <depend>ocs2_sphere_approximation</depend>
    <depend>ocs2_centroidal_model</depend>
    <depend>ocs2_self_collision</depend>
    <depend>ocs2_ros_interfaces</depend>

    <export>
      <wolf_planner_interface plugin="${prefix}/wolf_planner_perceptive_plugins.xml" />
    </export>

</package>
