<?xml version="1.0"?>
<package format="2">
    <name>wolf_planner</name>
    <version>0.0.1</version>
    <description>The wolf_planner package</description>
    <maintainer email="todo@gmail.com">ToDo</maintainer>
    <license>BSD</license>
    <author email="todo@gmail.com">ToDo</author>

    <buildtool_depend>catkin</buildtool_depend>
    <depend>roscpp</depend>
    <depend>wolf_planner_interface</depend>
    <depend>angles</depend>
    <depend>wolf_msgs</depend>
    <depend>wolf_controller_utils</depend>
    <depend>pinocchio</depend>
    <depend>hpp-fcl</depend>

    <export>
    </export>

</package>
